/**
 * generated by Xtext
 */
package no.hal.ra.xtext.validation;

import no.hal.ra.xtext.validation.AbstractXraValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class XraValidator extends AbstractXraValidator {
}
