/**
 * generated by Xtext
 */
package no.hal.pg.quiz.xtext.ui.contentassist;

import no.hal.pg.quiz.xtext.ui.contentassist.AbstractXQuizProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XQuizProposalProvider extends AbstractXQuizProposalProvider {
}
