language: java
sudo: false
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
script:
  - cd no.hal.pg.parent
  - mvn clean install
  - cd ../no.hal.quiz.parent
  - mvn clean install
  - cd ../no.hal.pg.quiz.parent
  - mvn clean install
