<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="platform:/plugin/no.hal.pg.quiz.model/model/quiz.ecore"
    nsPrefix="quizModel">
  <eClassifiers xsi:type="ecore:EClass" name="QuizTaskDef" eSuperTypes="../../no.hal.pg.model/model/pg.ecore#//TaskDef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="quizParts" upperBound="-1"
        eType="ecore:EClass ../../no.hal.quiz.model/model/quiz.ecore#//AbstractQuizPart"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="correctNeeded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attemptsAllowed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
