/**
 * generated by Xtext
 */
package no.hal.ra.xtext.serializer;

import no.hal.ra.xtext.serializer.AbstractXraSyntacticSequencer;

@SuppressWarnings("all")
public class XraSyntacticSequencer extends AbstractXraSyntacticSequencer {
}
