/**
 * generated by Xtext
 */
package no.hal.ra.xtext.serializer;

import no.hal.ra.xtext.serializer.AbstractXraSemanticSequencer;

@SuppressWarnings("all")
public class XraSemanticSequencer extends AbstractXraSemanticSequencer {
}
