/*
 * generated by Xtext
 */
package no.hal.ra.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class XraUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return no.hal.ra.xtext.ui.internal.XraActivator.getInstance().getInjector("no.hal.ra.xtext.Xra");
	}
	
}
