<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtime" nsURI="platform:/plugin/no.hal.pg.runtime/model/pg-runtime.ecore"
    nsPrefix="pg-runtime">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eOperations name="getTasks" upperBound="-1">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="stateClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player" containment="true" eOpposite="#//Player/game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        containment="true" eOpposite="#//Task/game">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" eType="#//Game" eOpposite="#//Game/players"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="ecore:EClass ../../no.hal.pg.model/model/pg.ecore#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//ITask">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PlayerIsContainedInGame"/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../no.hal.pg.model/model/pg.ecore#//TaskDef"/>
    </eTypeParameters>
    <eOperations name="changeState">
      <eParameters name="state">
        <eGenericType eClassifier="#//TaskState">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getCurrentState">
      <eGenericType eClassifier="#//TaskState">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskDef">
      <eGenericType eTypeParameter="#//Task/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" eType="#//Game" eOpposite="#//Game/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" containment="true"
        eOpposite="#//TaskAction/task">
      <eGenericType eClassifier="#//TaskAction">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        containment="true" eOpposite="#//TaskState/task">
      <eGenericType eClassifier="#//TaskState">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITask" abstract="true" interface="true">
    <eOperations name="isEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isStarted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isFinished" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="start"/>
    <eOperations name="isInState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="stateClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskState">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Task">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eOperations name="isFinishState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eOpposite="#//Task/states">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entered" eType="#//Timestamp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exited" eType="#//Timestamp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FinishedState">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Task">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//TaskState">
      <eTypeArguments eTypeParameter="#//FinishedState/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Timestamp" instanceClassName="java.lang.Long"/>
  <eClassifiers xsi:type="ecore:EClass" name="TaskAction" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PlayerIsContainedInGame"/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Task">
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eOperations name="prepare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="task">
        <eGenericType eClassifier="#//Task">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="perform" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eOpposite="#//Task/actions">
      <eGenericType eTypeParameter="#//TaskAction/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" eType="#//Player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UoD">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="ecore:EClass ../../no.hal.pg.model/model/pg.ecore#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="games" upperBound="-1"
        eType="#//Game" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
