<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtime" nsURI="platform:/plugin/no.hal.pg.runtime/model/pg-runtime.ecore"
    nsPrefix="pg-runtime">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
    <details key="pg-model" value="../../no.hal.pg.model/model/pg.ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Game" eSuperTypes="#//Players #//Services">
    <eOperations name="getTasks" upperBound="-1">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="stateClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player" containment="true" eOpposite="#//Player/game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        containment="true" eOpposite="#//Task/game">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" eType="#//Game" eOpposite="#//Game/players"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="ecore:EClass ../../no.hal.pg.model/model/pg.ecore#//Person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Players" abstract="true" interface="true">
    <eOperations name="getPlayers" upperBound="-1" eType="#//Player"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Services">
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        containment="true">
      <eGenericType eClassifier="#//Service">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Task" eSuperTypes="#//Players #//Services">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="PlayerIsContainedInGame"/>
    </eAnnotations>
    <eTypeParameters name="T">
      <eBounds eClassifier="ecore:EClass ../../no.hal.pg.model/model/pg.ecore#//TaskDef"/>
    </eTypeParameters>
    <eTypeParameters name="R"/>
    <eOperations name="isStarted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="isFinished" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="start"/>
    <eOperations name="changeState">
      <eParameters name="state">
        <eGenericType eClassifier="#//TaskState">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="getCurrentState">
      <eGenericType eClassifier="#//TaskState">
        <eTypeArguments/>
      </eGenericType>
    </eOperations>
    <eOperations name="isInState" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="stateClass" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskDef">
      <eGenericType eTypeParameter="#//Task/T"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" eType="#//Game" eOpposite="#//Game/tasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        containment="true" eOpposite="#//TaskState/task">
      <eGenericType eClassifier="#//TaskState">
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result">
      <eGenericType eTypeParameter="#//Task/R"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskState" eSuperTypes="#//Services">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task" eOpposite="#//Task/states">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entered" eType="#//Timestamp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exited" eType="#//Timestamp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Timestamp" instanceClassName="java.lang.Long"/>
  <eClassifiers xsi:type="ecore:EClass" name="Service" abstract="true" interface="true">
    <eTypeParameters name="T"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context">
      <eGenericType eTypeParameter="#//Service/T"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskService" abstract="true">
    <eTypeParameters name="T">
      <eBounds eClassifier="#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eBounds>
    </eTypeParameters>
    <eGenericSuperTypes eClassifier="#//Service">
      <eTypeArguments eTypeParameter="#//TaskService/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ref" abstract="true">
    <eTypeParameters name="T"/>
    <eOperations name="get">
      <eGenericType eTypeParameter="#//Ref/T"/>
      <eParameters name="context" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectRef">
    <eTypeParameters name="T"/>
    <eOperations name="get">
      <eGenericType eTypeParameter="#//DirectRef/T"/>
      <eParameters name="context" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref">
      <eGenericType eTypeParameter="#//DirectRef/T"/>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Ref">
      <eTypeArguments eTypeParameter="#//DirectRef/T"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eGenericSuperTypes eClassifier="#//Ref">
      <eTypeArguments eClassifier="#//Player"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameService">
    <eOperations name="getTasks" upperBound="-1">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="player">
        <eGenericType eClassifier="#//Ref">
          <eTypeArguments eClassifier="#//Player"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players" upperBound="-1"
        eType="#//Player" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks" upperBound="-1"
        changeable="false" volatile="true" transient="true" derived="true">
      <eGenericType eClassifier="#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//Service">
      <eTypeArguments eClassifier="#//Game"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
