<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="service"
    nsURI="platform:/plugin/no.hal.pg.runtime/model/pg-service.ecore"
    nsPrefix="pg-service">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="GameService">
    <eOperations
        name="getTasks"
        upperBound="-1">
      <eGenericType
          eClassifier="ecore:EClass pg-runtime.ecore#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
      <eParameters
          name="player"
          eType="ecore:EClass pg-runtime.ecore#//Player"/>
    </eOperations>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="players"
        upperBound="-1"
        eType="ecore:EClass pg-runtime.ecore#//Player"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="tasks"
        upperBound="-1"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true">
      <eGenericType
          eClassifier="ecore:EClass pg-runtime.ecore#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes
        eClassifier="ecore:EClass pg-runtime.ecore#//Service">
      <eTypeArguments
          eClassifier="ecore:EClass pg-runtime.ecore#//Game"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="TaskService">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="players"
        upperBound="-1"
        eType="ecore:EClass pg-runtime.ecore#//Player"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="started"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="finished"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="result"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"/>
    <eGenericSuperTypes
        eClassifier="ecore:EClass pg-runtime.ecore#//Service">
      <eTypeArguments
          eClassifier="ecore:EClass pg-runtime.ecore#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eTypeArguments>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="PlayerService">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="tasks"
        upperBound="-1"
        changeable="false"
        volatile="true"
        transient="true"
        derived="true">
      <eGenericType
          eClassifier="ecore:EClass pg-runtime.ecore#//Task">
        <eTypeArguments/>
        <eTypeArguments/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes
        eClassifier="ecore:EClass pg-runtime.ecore#//Service">
      <eTypeArguments
          eClassifier="ecore:EClass pg-runtime.ecore#//Player"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
