/*
 * generated by Xtext
 */
package no.hal.ra.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import no.hal.ra.xtext.services.XraGrammarAccess;

public class XraParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private XraGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected no.hal.ra.xtext.parser.antlr.internal.InternalXraParser createParser(XtextTokenStream stream) {
		return new no.hal.ra.xtext.parser.antlr.internal.InternalXraParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Department";
	}
	
	public XraGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(XraGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
