<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pgo" nsURI="platform:/plugin/no.hal.pgo.model/model/pgo.ecore"
    nsPrefix="pgo">
  <eClassifiers xsi:type="ecore:EClass" name="PType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="species" upperBound="-1"
        eType="#//PSpecies" containment="true" eOpposite="#//PSpecies/type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PSpecies">
    <eStructuralFeatures xsi:type="ecore:EReference" name="evolvesTo" eType="#//PSpecies"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//PType"
        eOpposite="#//PType/species"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="P">
    <eStructuralFeatures xsi:type="ecore:EReference" name="species" eType="#//PSpecies"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ball" eSuperTypes="#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ids" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="#//Person"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ps" eType="#//P"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PGame">
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//PType" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
