/*
 * generated by Xtext
 */
package no.hal.ra.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import no.hal.ra.xtext.services.XraGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public abstract class AbstractXraSyntacticSequencer extends AbstractSyntacticSequencer {

	protected XraGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Person___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_4__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (XraGrammarAccess) access;
		match_Person___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_4__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPersonAccess().getLeftParenthesisKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getPersonAccess().getRightParenthesisKeyword_2_4()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if(match_Person___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_4__q.equals(syntax))
				emit_Person___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_4__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=EString (ambiguity) 'works' employmentFactor=Factor
	 */
	protected void emit_Person___LeftParenthesisKeyword_2_0_RightParenthesisKeyword_2_4__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
