/*
 * generated by Xtext
 */
package no.hal.ra.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XraUiModule extends no.hal.ra.xtext.ui.AbstractXraUiModule {
	public XraUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
