/*
 * generated by Xtext
 */
package no.hal.pg.quiz.xtext;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.resource.IFragmentProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class XQuizRuntimeModule extends no.hal.pg.quiz.xtext.AbstractXQuizRuntimeModule {

	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return no.hal.pg.quiz.xtext.serializer.XQuizValueConverter.class;
	}

	@Override
	public Class<? extends IFragmentProvider> bindIFragmentProvider() {
		return no.hal.pg.quiz.xtext.scoping.XQuizFragmentProvider.class;
	}
}
