/*
 * generated by Xtext
 */
package no.hal.pg.quiz.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class XQuizStandaloneSetup extends XQuizStandaloneSetupGenerated{

	public static void doSetup() {
		new XQuizStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

