<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="service" nsURI="platform:/plugin/no.hal.pg.quiz.runtime/model/quiz-service.ecore"
    nsPrefix="quiz-service">
  <eClassifiers xsi:type="ecore:EClass" name="QuizTaskService">
    <eOperations name="proposeAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="player" eType="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Player"/>
      <eParameters name="qa" eType="ecore:EClass ../../no.hal.quiz.model/model/quiz.ecore#//QA"/>
      <eParameters name="proposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="acceptAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="player" eType="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Player"/>
      <eParameters name="qa" eType="ecore:EClass ../../no.hal.quiz.model/model/quiz.ecore#//QA"/>
      <eParameters name="proposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getQAProposals" upperBound="-1" eType="ecore:EClass quiz-runtime.ecore#//QAProposal">
      <eParameters name="player" eType="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Player"/>
    </eOperations>
    <eOperations name="getPlayerQuestions" upperBound="-1" eType="#//Question">
      <eParameters name="player" eType="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Player"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Service">
      <eTypeArguments eClassifier="ecore:EClass quiz-runtime.ecore#//QuizTask"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QAProposalService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="proposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accepted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rejectedCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Service">
      <eTypeArguments eClassifier="ecore:EClass quiz-runtime.ecore#//QAProposal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//AnswerKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastProposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Answer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numChoices" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="answer" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AnswerKind">
    <eLiterals name="STRING" literal="STRING"/>
    <eLiterals name="NUM" value="1" literal="NUM"/>
    <eLiterals name="YESNO" value="2" literal="YESNO"/>
  </eClassifiers>
</ecore:EPackage>
