<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="service" nsURI="platform:/plugin/no.hal.pg.quiz.runtime/model/quiz-service.ecore"
    nsPrefix="quiz-service">
  <eClassifiers xsi:type="ecore:EClass" name="QuizTaskService">
    <eOperations name="proposeAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="player" eType="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Player"/>
      <eParameters name="qa" eType="ecore:EClass ../../no.hal.quiz.model/model/quiz.ecore#//QA"/>
      <eParameters name="proposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="acceptAnswer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="player" eType="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Player"/>
      <eParameters name="qa" eType="ecore:EClass ../../no.hal.quiz.model/model/quiz.ecore#//QA"/>
      <eParameters name="proposal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getQAProposals" upperBound="-1" eType="ecore:EClass quiz-runtime.ecore#//QAProposal">
      <eParameters name="player" eType="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Player"/>
    </eOperations>
    <eGenericSuperTypes eClassifier="ecore:EClass ../../no.hal.pg.runtime/model/pg-runtime.ecore#//Service">
      <eTypeArguments eClassifier="ecore:EClass quiz-runtime.ecore#//QuizTask"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
