/*
 * generated by Xtext
 */
package no.hal.ra.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import no.hal.ra.xtext.ui.internal.XraActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XraExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XraActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XraActivator.getInstance().getInjector(XraActivator.NO_HAL_RA_XTEXT_XRA);
	}
	
}
