/*
 * generated by Xtext
 */
package no.hal.quiz.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class XQuizUiModule extends no.hal.quiz.xtext.ui.AbstractXQuizUiModule {
	public XQuizUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
