/*
 * generated by Xtext
 */
package no.hal.quiz.xtext.ui.contentassist

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class XQuizProposalProvider extends AbstractXQuizProposalProvider {
}
