/**
 * generated by Xtext
 */
package no.hal.pg.quiz.xtext.serializer;

import no.hal.pg.quiz.xtext.serializer.AbstractXQuizSyntacticSequencer;

@SuppressWarnings("all")
public class XQuizSyntacticSequencer extends AbstractXQuizSyntacticSequencer {
}
